version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - myapp-storage:/var/www/html/storage

    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: task
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

volumes:
  myapp-storage: